2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Configure stats pid to 28924
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Loading settings from C:\Users\kibona9\.config\wandb\settings
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Loading settings from C:\GiHub repos\MLOps_Assignment\wandb\settings
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train_ver2.py', 'program_abspath': 'c:\\GiHub repos\\MLOps_Assignment\\train_ver2.py', 'program': 'c:\\GiHub repos\\MLOps_Assignment\\train_ver2.py'}
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-31 23:22:29,950 INFO    MainThread:28924 [wandb_init.py:_log_setup():534] Logging user logs to C:\GiHub repos\MLOps_Assignment\wandb\run-20241031_232229-ke0pqh0j\logs\debug.log
2024-10-31 23:22:29,952 INFO    MainThread:28924 [wandb_init.py:_log_setup():535] Logging internal logs to C:\GiHub repos\MLOps_Assignment\wandb\run-20241031_232229-ke0pqh0j\logs\debug-internal.log
2024-10-31 23:22:29,952 INFO    MainThread:28924 [wandb_init.py:init():621] calling init triggers
2024-10-31 23:22:29,952 INFO    MainThread:28924 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'batch_size': 64, 'epochs': 10, 'dropout_rate': 0.2}
2024-10-31 23:22:29,952 INFO    MainThread:28924 [wandb_init.py:init():671] starting backend
2024-10-31 23:22:29,952 INFO    MainThread:28924 [wandb_init.py:init():675] sending inform_init request
2024-10-31 23:22:29,954 INFO    MainThread:28924 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-31 23:22:29,954 INFO    MainThread:28924 [wandb_init.py:init():688] backend started and connected
2024-10-31 23:22:29,956 INFO    MainThread:28924 [wandb_init.py:init():783] updated telemetry
2024-10-31 23:22:29,980 INFO    MainThread:28924 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-10-31 23:22:30,535 WARNING MainThread:28924 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\site-packages\wandb\sdk\wandb_init.py", line 819, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kibona9\AppData\Local\anaconda3\envs\kibona_1\Lib\threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-10-31 23:22:30,580 WARNING MsgRouterThr:28924 [router.py:message_loop():77] message_loop has been closed
